baseurl         = "https://www.basestation.space"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Basestation Networking"
  subtitle    = ""
  copyright   = "Basestation Networking (© Copyright 2020)"

  cover       = "web_banner.png"
  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = "basestationspace"
  linkedinName = ""
  mediumName = ""

  logo = "logo.png"
  orgName = ""
  orgWebsite = ""
  orgDescription = ""

  showSupport = true

  author = ""
  authorAvatar = ""
  authorLocation = ""
  authorWebsite = ""
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About Us"
  url = "/about/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99


